// The CareerVeda mark, served from ImageKit. Kept in one place because the
// brand lockup appears in the navbar and in two footers, and a logo that is
// only updated in two of the three is the classic way these drift apart.
//
// `tr=w-96` asks ImageKit for a 96px-wide copy: the mark renders at 36px, so
// this still covers a 2x display without shipping the full-size original.
// updatedAt is ImageKit's cache-buster        keep it, or a replaced logo can sit
// stale in the CDN and in visitors' browsers.

// The navbar/footer lockup: the "CareerVeda / Learn. Analyze. Lead." wordmark,
// generated by scripts/make-logo.mjs (`npm run logo`) from the brand hexes and
// the site's own Manrope. It is served from public/ rather than ImageKit so the
// header does not wait on a third-party host for the first thing you see, and
// so the asset is versioned next to the code that draws it.
//
// Exported at 2x with a transparent background and a ~3.55:1 aspect ratio        the
// CSS sizes it by height and lets the width follow, so this ratio is the only
// thing the stylesheets need to agree with.
export const BRAND_LOGO_URL = "/brand/careerveda-logo.png";

// The icon to the left of the wordmark, now that the lockup is live text rather
// than the generated PNG above. Left empty until the asset exists: an <img> with
// a missing src paints a broken-image glyph in the navbar on every page, so the
// components render it only when this is set.
export const BRAND_ICON_URL = "https://ik.imagekit.io/q7ucn1rfni/careerveda/brand/logo.png?tr=w-90,f-auto,q-80";

// Favicon stays on the existing cvfavicon mark; change this too if you want the
// browser-tab icon to match the new logo.
const FAVICON_BASE = "https://ik.imagekit.io/q7ucn1rfni/careerveda/brand/cvfavicon-039eb18e.jpg";
export const BRAND_FAVICON_URL = `${FAVICON_BASE}?tr=w-64&updatedAt=1783702268532`;
